import type { Config } from 'tailwindcss'

const config: Config = {
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        primary: {
          50: '#f0f9ff',
          100: '#e0f2fe',
          200: '#bae6fd',
          300: '#7dd3fc',
          400: '#38bdf8',
          500: '#0ea5e9',
          600: '#0284c7',
          700: '#0369a1',
          800: '#075985',
          900: '#0c4a6e',
        },
        secondary: {
          50: '#fdf4ff',
          100: '#fae8ff',
          200: '#f5d0fe',
          300: '#f0abfc',
          400: '#e879f9',
          500: '#d946ef',
          600: '#c026d3',
          700: '#a21caf',
          800: '#86198f',
          900: '#701a75',
        },
        accent: {
          50: '#f0fdfa',
          100: '#ccfbf1',
          200: '#99f6e4',
          300: '#5eead4',
          400: '#2dd4bf',
          500: '#14b8a6',
          600: '#0d9488',
          700: '#0f766e',
          800: '#115e59',
          900: '#134e4a',
        },
        success: {
          50: '#ecfdf5',
          100: '#d1fae5',
          200: '#a7f3d0',
          300: '#6ee7b7',
          400: '#34d399',
          500: '#10b981',
          600: '#059669',
          700: '#047857',
          800: '#065f46',
          900: '#064e3b',
        },
        warning: {
          50: '#fffbeb',
          100: '#fef3c7',
          200: '#fde68a',
          300: '#fcd34d',
          400: '#fbbf24',
          500: '#f59e0b',
          600: '#d97706',
          700: '#b45309',
          800: '#92400e',
          900: '#78350f',
        },
        error: {
          50: '#fef2f2',
          100: '#fee2e2',
          200: '#fecaca',
          300: '#fca5a5',
          400: '#f87171',
          500: '#ef4444',
          600: '#dc2626',
          700: '#b91c1c',
          800: '#991b1b',
          900: '#7f1d1d',
        },
        gradient: {
          primary: 'var(--gradient-primary)',
          secondary: 'var(--gradient-secondary)',
          accent: 'var(--gradient-accent)',
          success: 'var(--gradient-success)',
          warning: 'var(--gradient-warning)',
          error: 'var(--gradient-error)',
          rainbow: 'var(--gradient-rainbow)',
          ocean: 'var(--gradient-ocean)',
          sunset: 'var(--gradient-sunset)',
          medical: 'var(--gradient-medical)',
        },
        background: '#f8fafc',
        foreground: '#0f172a',
        medical: {
          blue: '#0ea5e9',
          green: '#10b981',
          purple: '#d946ef',
          pink: '#ec4899',
          orange: '#f59e0b',
          teal: '#14b8a6',
          indigo: '#6366f1',
          red: '#ef4444',
        }
      },
      fontFamily: {
        'bangla': ['Kalpurush', 'SolaimanLipi', 'sans-serif'],
        'sans': ['Inter', 'Poppins', 'sans-serif'],
        'display': ['Poppins', 'Inter', 'sans-serif'],
      },
      spacing: {
        '18': '4.5rem',
        '88': '22rem',
        '112': '28rem',
        '128': '32rem',
      },
      borderRadius: {
        '4xl': '2rem',
        '5xl': '2.5rem',
      },
      animation: {
        'fade-in': 'fadeIn 0.5s ease-in-out',
        'fade-in-up': 'fadeInUp 0.6s ease-out',
        'fade-in-scale': 'fadeInScale 0.8s ease-out',
        'fade-in-down': 'fadeInDown 0.6s ease-out',
        'slide-in-left': 'slideInLeft 0.6s ease-out',
        'slide-in-right': 'slideInRight 0.6s ease-out',
        'slide-in-up': 'slideInUp 0.6s ease-out',
        'slide-in-down': 'slideInDown 0.6s ease-out',
        'zoom-in': 'zoomIn 0.6s ease-out',
        'rotate-in': 'rotateIn 0.8s ease-out',
        'bounce-in': 'bounceIn 0.8s ease-out',
        'float': 'float 3s ease-in-out infinite',
        'float-reverse': 'floatReverse 3s ease-in-out infinite',
        'pulse-subtle': 'pulseSubtle 2s ease-in-out infinite',
        'shimmer': 'shimmer 1.5s infinite',
        'bounce-gentle': 'bounceGentle 0.6s ease-in-out',
        'glow': 'glow 2s ease-in-out infinite alternate',
        'glow-secondary': 'glowSecondary 2s ease-in-out infinite alternate',
        'glow-accent': 'glowAccent 2s ease-in-out infinite alternate',
        'spin-slow': 'spin 3s linear infinite',
        'ping-slow': 'ping 3s cubic-bezier(0, 0, 0.2, 1) infinite',
        'scale-in': 'scaleIn 0.3s ease-out',
        'scale-out': 'scaleOut 0.3s ease-in',
        'wiggle': 'wiggle 1s ease-in-out infinite',
        'heartbeat': 'heartbeat 1.5s ease-in-out infinite',
      },
      keyframes: {
        fadeIn: {
          'from': { opacity: '0', transform: 'translateY(20px)' },
          'to': { opacity: '1', transform: 'translateY(0)' },
        },
        fadeInUp: {
          'from': { opacity: '0', transform: 'translateY(30px)' },
          'to': { opacity: '1', transform: 'translateY(0)' },
        },
        fadeInDown: {
          'from': { opacity: '0', transform: 'translateY(-30px)' },
          'to': { opacity: '1', transform: 'translateY(0)' },
        },
        fadeInScale: {
          'from': { opacity: '0', transform: 'scale(0.8) translateY(30px)' },
          'to': { opacity: '1', transform: 'scale(1) translateY(0)' },
        },
        slideInLeft: {
          'from': { opacity: '0', transform: 'translateX(-50px)' },
          'to': { opacity: '1', transform: 'translateX(0)' },
        },
        slideInRight: {
          'from': { opacity: '0', transform: 'translateX(50px)' },
          'to': { opacity: '1', transform: 'translateX(0)' },
        },
        slideInUp: {
          'from': { opacity: '0', transform: 'translateY(50px)' },
          'to': { opacity: '1', transform: 'translateY(0)' },
        },
        slideInDown: {
          'from': { opacity: '0', transform: 'translateY(-50px)' },
          'to': { opacity: '1', transform: 'translateY(0)' },
        },
        zoomIn: {
          'from': { opacity: '0', transform: 'scale(0.3)' },
          'to': { opacity: '1', transform: 'scale(1)' },
        },
        rotateIn: {
          'from': { opacity: '0', transform: 'rotate(-200deg)' },
          'to': { opacity: '1', transform: 'rotate(0)' },
        },
        bounceIn: {
          '0%': { opacity: '0', transform: 'scale(0.3) translateY(-50px)' },
          '50%': { opacity: '1', transform: 'scale(1.05) translateY(0)' },
          '70%': { transform: 'scale(0.9)' },
          '100%': { transform: 'scale(1)' },
        },
        float: {
          '0%, 100%': { transform: 'translateY(0px)' },
          '50%': { transform: 'translateY(-10px)' },
        },
        floatReverse: {
          '0%, 100%': { transform: 'translateY(0px)' },
          '50%': { transform: 'translateY(10px)' },
        },
        pulseSubtle: {
          '0%, 100%': { opacity: '1' },
          '50%': { opacity: '0.8' },
        },
        shimmer: {
          '0%': { backgroundPosition: '-200px 0' },
          '100%': { backgroundPosition: 'calc(200px + 100%) 0' },
        },
        bounceGentle: {
          '0%, 100%': { transform: 'translateY(0)' },
          '50%': { transform: 'translateY(-10px)' },
        },
        glow: {
          '0%': { boxShadow: '0 0 5px rgba(14, 165, 233, 0.3)' },
          '100%': { boxShadow: '0 0 20px rgba(14, 165, 233, 0.6), 0 0 30px rgba(14, 165, 233, 0.4)' },
        },
        glowSecondary: {
          '0%': { boxShadow: '0 0 5px rgba(217, 70, 239, 0.3)' },
          '100%': { boxShadow: '0 0 20px rgba(217, 70, 239, 0.6), 0 0 30px rgba(217, 70, 239, 0.4)' },
        },
        glowAccent: {
          '0%': { boxShadow: '0 0 5px rgba(20, 184, 166, 0.3)' },
          '100%': { boxShadow: '0 0 20px rgba(20, 184, 166, 0.6), 0 0 30px rgba(20, 184, 166, 0.4)' },
        },
        scaleIn: {
          'from': { transform: 'scale(0)' },
          'to': { transform: 'scale(1)' },
        },
        scaleOut: {
          'from': { transform: 'scale(1)' },
          'to': { transform: 'scale(0)' },
        },
        wiggle: {
          '0%, 100%': { transform: 'rotate(-3deg)' },
          '50%': { transform: 'rotate(3deg)' },
        },
        heartbeat: {
          '0%, 100%': { transform: 'scale(1)' },
          '14%': { transform: 'scale(1.1)' },
          '28%': { transform: 'scale(1)' },
          '42%': { transform: 'scale(1.1)' },
          '70%': { transform: 'scale(1)' },
        },
      },
      boxShadow: {
        'soft': '0 2px 15px rgba(0, 0, 0, 0.08)',
        'medium': '0 4px 25px rgba(0, 0, 0, 0.1)',
        'large': '0 8px 40px rgba(0, 0, 0, 0.12)',
        'extra': '0 20px 50px rgba(0, 0, 0, 0.15)',
        'inner-soft': 'inset 0 2px 4px rgba(0, 0, 0, 0.06)',
        'glow-primary': '0 0 20px rgba(59, 130, 246, 0.3)',
        'glow-secondary': '0 0 20px rgba(16, 185, 129, 0.3)',
        'glow-accent': '0 0 20px rgba(245, 158, 11, 0.3)',
      },
      backdropBlur: {
        xs: '2px',
      },
    },
  },
  plugins: [require('daisyui')],
  daisyui: {
    themes: [
      {
        PrescribeCorrect: {
          primary: '#0ea5e9',
          'primary-focus': '#0284c7',
          'primary-content': '#ffffff',
          secondary: '#d946ef',
          'secondary-focus': '#c026d3',
          'secondary-content': '#ffffff',
          accent: '#14b8a6',
          'accent-focus': '#0d9488',
          'accent-content': '#ffffff',
          neutral: '#475569',
          'neutral-focus': '#334155',
          'neutral-content': '#f1f5f9',
          'base-100': '#ffffff',
          'base-200': '#f8fafc',
          'base-300': '#e2e8f0',
          'base-content': '#0f172a',
          info: '#0ea5e9',
          'info-content': '#ffffff',
          success: '#10b981',
          'success-content': '#ffffff',
          warning: '#f59e0b',
          'warning-content': '#ffffff',
          error: '#ef4444',
          'error-content': '#ffffff',
        },
      },
      {
        'PrescribeCorrect-dark': {
          primary: '#38bdf8',
          'primary-focus': '#0ea5e9',
          'primary-content': '#0f172a',
          secondary: '#e879f9',
          'secondary-focus': '#d946ef',
          'secondary-content': '#0f172a',
          accent: '#2dd4bf',
          'accent-focus': '#14b8a6',
          'accent-content': '#0f172a',
          neutral: '#1e293b',
          'neutral-focus': '#0f172a',
          'neutral-content': '#f1f5f9',
          'base-100': '#0f172a',
          'base-200': '#1e293b',
          'base-300': '#334155',
          'base-content': '#f1f5f9',
          info: '#38bdf8',
          'info-content': '#0f172a',
          success: '#34d399',
          'success-content': '#0f172a',
          warning: '#fbbf24',
          'warning-content': '#0f172a',
          error: '#f87171',
          'error-content': '#0f172a',
        },
      },
    ],
    base: true,
    styled: true,
    utils: true,
    prefix: '',
    logs: false,
  },
}

export default config
